mahdia_profile/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    url(r'^blog/$', views.blog, name='blog'),
    url(r'^schedule/$', views.schedule, name='schedule'),
    # path('delete/<int:id>', views.delete_activity, name='delete'),
    path('delete/', views.delete_activity, name='delete'),
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mahdia_profile.urls'))
]

mahdia_profile/models.py
from django.db import models

# Create your models here.


class Activity(models.Model):
    title = models.CharField(max_length=55)
    date = models.DateField()
    time = models.TimeField()
    location = models.CharField(max_length=55)
    category = models.CharField(max_length=30)

    def __str__(self):
        return self.title

mahdia_profile/forms.py
from django import forms


class CreateActivity(forms.Form):
    title = forms.CharField(max_length=55)
    date = forms.DateTimeField(input_formats=['%Y-%m-%d'])
    time = forms.TimeField()
    location = forms.CharField(max_length=55)
    category = forms.CharField(max_length=30)

    date.widget.attrs.update({'autocomplete': 'off', 'placeholder': 'date'})

mahdia_profile/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import CreateActivity
from .models import Activity

# Create your views here.


def homepage(request):
    return render(request, 'index.html')


def blog(request):
    return render(request, 'blog.html')


def schedule(request):
    if request.method == 'POST':
        form = CreateActivity(request.POST)
        if form.is_valid():
            act = Activity(
                title=form.data["title"],
                date=form.data["date"],
                time=form.data["time"],
                location=form.data["location"],
                category=form.data["category"],
            )
            act.save()
            form = CreateActivity()

    else:
        form = CreateActivity()

    activities = Activity.objects.all()

    context = {
        'form': form,
        'activities': activities,
    }
    print(request.POST)
    return render(request, 'schedule.html', context)


def delete_activity(request):
    if request.method == 'POST' and 'id' in request.POST:
        Activity.objects.get(id=request.POST['id']).delete()
    return redirect(reverse('schedule'))

mahdia_profile/templates/blog.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Red+Hat+Text:400,500,700&display=swap" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <title>Mahdia Aliyya | Blog </title>
</head>

<body class="position-relative">
    <!-- Navigation bar -->
    {% include "header.html" %}

    <!-- Blog content -->
    <div id="blog">
        <h2>Blog</h2>
        <div class="dark-bg blog-content">
            <div class="d-flex flex-wrap flex-row justify-content-between">
                <div class="blog-preview">
                    <div class="preview-pic">
                        <img src="{% static 'assets/citylight.jpg' %}">
                    </div>
                    <div class="preview-text">
                        <p>Dummy text preview here.</p>
                        <a>Read more ></a>
                    </div>
                </div>
                <div class="blog-preview">
                    <div class="preview-pic">
                        <img src="{% static 'assets/citylight.jpg' %}">
                    </div>
                    <div class="preview-text">
                        <p>Dummy text preview here.</p>
                        <a>Read more ></a>
                    </div>
                </div>
                <div class="blog-preview">
                    <div class="preview-pic">
                        <img src="{% static 'assets/citylight.jpg' %}">
                    </div>
                    <div class="preview-text">
                        <p>Dummy text preview here.</p>
                        <a>Read more ></a>
                    </div>
                </div>
            </div>
            <a href="https://medium.com/@mahdiaaliyya" target="_blank" class="float-right"><b>Follow my medium ></b></a>
        </div>
    </div>

    <!-- Footer -->
    <footer>
        <p>© 2019 by Mahdia Aliyya</p>
    </footer>

</body>

</html>

mahdia_profile/templates/header.html
{% load static %}

<div class="navbar">
    <a href="{% url 'homepage' %}">
        <img src="{% static 'assets/mhd.png' %}" alt="mhd">
    </a>
    <div class="navigations">
        <a href="{% url 'homepage' %}#about">about</a>
        <a href="{% url 'homepage' %}#experience">experience</a>
        <a href="{% url 'homepage' %}#contact">contact</a>
        <a href="{% url 'schedule' %}">schedule</a>
        <a href="{% url 'blog' %}">blog</a>
    </div>
</div>

mahdia_profile/templates/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Red+Hat+Text:400,500,700&display=swap" rel="stylesheet">

    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <title>Mahdia Aliyya</title>
</head>

<body class="position-relative">
    <!-- Navigation bar -->
    {% include "header.html" %}


    <!-- Home Section -->
    <div id="home" class="position-relative justify-content-center">
        <div class="d-flex flex-column ">
            <div class="d-flex flex-wrap justify-content-around">
                <div class="profile-photo">
                    <img src="{% static 'assets/MahdiaAliyya.jpg' %}" alt="Mahdia Aliyya">
                </div>
                <div class="title">
                    <h1>Hi, I'm<br>Mahdia Aliyya</h1>
                    <h4>Computer Science Student</h4>
                    <button>Download CV</button>
                </div>
            </div>
            <div class="button-container d-flex flex-wrap justify-content-center">
                <button class="button-scroll-down">
                    <a href="#about"><i class="fa fa-chevron-down"></i></a>
                </button>
            </div>
        </div>
        <div class="icon-vertical d-flex flex-column">
            <button onclick="window.location.href = 'https://www.linkedin.com/in/mahdiaaliyya/';">
                <i class="fa fa-linkedin"></i>
            </button>
            <button><i class="fa fa-twitter"></i></button>
            <button onclick="window.location.href = 'https://gitlab.com/mahdiaaliyya';">
                <i class="fa fa-gitlab"></i>
            </button>
            <button onclick="window.location.href = 'https://github.com/mahdiaaliyya';">
                <i class="fa fa-github"></i>
            </button>
        </div>

    </div>

    <!-- About Me Section -->
    <div id="about">
        <div class="container">
            <div class="col-sm-12">
                <h2>About me</h2>
                <p>
                    I’m currently studying computer science at University of Indonesia. I highly interested in
                    <b>web development and design</b>
                    and about to find out more about other fields. In my spare time, i like to
                    read Paulo Coelho's books, binge watch tv series, listen to Bruno Major, or just play with my
                    cats.
                    I’m
                    passionate at
                    what I do and am really excited to learn new things.
                </p>
            </div>
        </div>
    </div>

    <!-- Experience and Skills Section -->
    <div id="experience">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-sm-12 experience-container">
                    <h2>Experience</h2>
                    <ul>
                        <li>
                            <p><b>Front End Intern, Happy 5</b></p>
                            <p>June - August 2019<br>
                                Created create objective page using
                                React hooks</p>
                        </li>
                        <li>
                            <p><b>Front End Developer, IT Force FUKI</b></p>
                            <p>January 2019 - now<br>
                                Created a web app with Django</p>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-6 col-sm-12 experience-container">
                    <h2>Skills</h2>
                    <ul>
                        <li>
                            <p><b>Intermediate</b></p>
                            <p>HTML5, CSS, React hooks, Java, Python</p>
                        </li>
                        <li>
                            <p><b>Beginner</b></p>
                            <p>Django, Javascript</p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <!-- Contact ME Section -->
    <div id="contact" class="position-relative">
        <div class="container">
            <h2 class="row">Contact me</h2>
            <div class="row">
                <div class="col-lg-7 col-sm-12 form-container">
                    <form id="contact-form">
                        <input type="text" placeholder="Name" id="form-name" name="name">
                        <input type="email" placeholder="Email" id="form-email" name="email">
                        <textarea type="text" placeholder="Message" id="form-message" name="msg"></textarea>
                    </form>
                    <button id="submit-btn">Submit</button>
                </div>
                <div class="col-lg-5 col-sm-12">
                    <p>mahdia.aliyya@gmail.com<br>(+62) 852 8810 5186</p>
                    <div class="icon-horizontal">
                        <button onclick="window.location.href = 'https://www.linkedin.com/in/mahdiaaliyya/';">
                            <i class="fa fa-linkedin"></i>
                        </button>
                        <button><i class="fa fa-twitter"></i></button>
                        <button onclick="window.location.href = 'https://gitlab.com/mahdiaaliyya';">
                            <i class="fa fa-gitlab"></i>
                        </button>
                        <button onclick="window.location.href = 'https://github.com/mahdiaaliyya';">
                            <i class="fa fa-github"></i>
                        </button>
                    </div>
                </div>
            </div>
            <div class="button-scroll-up-container d-flex flex-wrap justify-content-center">
                <button class="button-scroll-up">
                    <a href="#home"><i class="fa fa-chevron-up"></i></a>
                </button>
            </div>
        </div>
    </div>

    <!-- Footer -->
    <footer>
        <p>© 2019 by Mahdia Aliyya</p>
    </footer>

</body>

</html>

mahdia_profile/templates/schedule.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Red+Hat+Text:400,500,700&display=swap" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css"
        integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js"
        integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
    <title>Mahdia Aliyya | Schedule </title>
</head>

<body class="position-relative">
    <!-- Navigation bar -->
    {% include "header.html" %}

    <!-- Blog content -->
    <div id="schedule">
        <h2>Schedule</h2>
        <div>
            <form id="schedule-form" action="{% url 'schedule' %}" method="POST">
                {% csrf_token %}
                {{ form }}
                <input type="submit" name="submit" value="Submit">
            </form>
        </div>

        {% regroup activities|dictsort:"date" by date as activity_list %}
        {% for activity_date in activity_list %}
        <h3>{{ activity_date.grouper|date:"D, d M Y" }}</h3>
        {% for activity in activity_date.list %}
        <div class=event-card>
            <div>
                <h4>{{ activity.title }}</h4>
                <p>{{ activity.time }} | {{ activity.location }}</p>
            </div>
            <div class="right-side-card">
                <p>{{ activity.category }}</p>
                <form action="{% url 'delete' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" value="{{ activity.id }}" name="id">
                    <button type="submit" class="delete-button">
                        <svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <circle cx="8.99992" cy="8.99998" r="8" transform="rotate(-1.75953 8.99992 8.99998)"
                                fill="#C4C4C4" />
                            <path
                                d="M6.58951 12.1092L5.83439 11.3371L8.17653 9.04657L6.0622 6.88459L6.86007 6.1043L8.97441 8.26628L11.2651 6.02609L12.0202 6.79822L9.72953 9.03841L11.8313 11.1875L11.0334 11.9678L8.93166 9.81871L6.58951 12.1092Z"
                                fill="white" />
                        </svg>

                    </button>
                </form>
            </div>
        </div>
        {% endfor %}
        {% endfor %}
    </div>

    <!-- Footer -->
    <footer>
        <p>© 2019 by Mahdia Aliyya</p>
    </footer>

    <script>
        $(function () {
            $("#id_date").datepicker({
                format: 'yyyy-mm-dd',
            });
        });
    </script>

</body>

</html>